import { theme } from "../theme/theme";

export const styles = {
  content: {
    width: "100%",
    minWidth: 0,
  },
  page: {
    minHeight: "100dvh",
    boxSizing: "border-box" as const,
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: theme.layout.pagePadding,
    background: theme.colors.desktopBg,
  },
  phone: {
    width: "100%",
    maxWidth: theme.layout.contentMaxWidth,
    minHeight: "calc(100dvh - 48px)",
    boxSizing: "border-box" as const,
    borderRadius: theme.layout.phoneRadius,
    padding: theme.layout.phonePadding,
    background: theme.colors.phoneBg,
    color: theme.colors.text,
    border: `1px solid ${theme.colors.border}`,
    boxShadow: `0 24px 60px ${theme.colors.shadow}, inset 0 1px 0 ${theme.colors.inset}`,
    display: "flex",
    flexDirection: "column" as const,
    justifyContent: "flex-start",
    alignItems: "stretch",
    gap: 16,
    fontFamily: theme.type.fontFamily,
  },
  title: {
    fontSize: 32,
    fontWeight: 700,
    margin: 0,
  },
  subtitle: {
    fontSize: 16,
    opacity: 0.85,
    marginBottom: 24,
    textAlign: "center" as const,
  },
  button: {
    padding: "14px 24px",
    fontSize: 18,
    fontWeight: 600,
    borderRadius: 14,
    border: "none",
    background: theme.colors.primary,
    color: theme.colors.text,
    cursor: "pointer",
  },
} as const;
