import { theme } from "../theme/theme";

export const styles = {
  header: {
    width: "100%",
    minHeight: 72,
    paddingBottom: 12,
    display: "flex",
    flexDirection: "column" as const,
    justifyContent: "center",
  },
  footer: {
    width: "100%",
    paddingTop: 12,
    paddingBottom: 8,
    display: "flex",
    justifyContent: "center",
  },
  content: {
    width: "100%",
    flex: 1,
    overflowY: "auto" as const,
    overscrollBehavior: "contain" as const,
    WebkitOverflowScrolling: "touch" as const,
    paddingBottom: 16,
  },
  page: {
    minHeight: "100vh",
    width: "100vw",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    padding: theme.layout.pagePadding,
    background: theme.colors.desktopBg,
  },
  phone: {
    width: theme.layout.phoneWidth,
    maxWidth: "100vw",
    height: "min(844px, 100vh - 48px)",
    borderRadius: theme.layout.phoneRadius,
    padding: theme.layout.phonePadding,
    background: theme.colors.phoneBg,
    color: theme.colors.text,
    border: `1px solid ${theme.colors.border}`,
    boxShadow: `0 24px 60px ${theme.colors.shadow}, inset 0 1px 0 ${theme.colors.inset}`,
    display: "flex",
    flexDirection: "column" as const,
    justifyContent: "flex-start",
    alignItems: "strech",
    fontFamily: theme.type.fontFamily,
    overflow: "hidden",
  },
  title: {
    fontSize: 32,
    fontWeight: 700,
    margin: 0,
  },
  subtitle: {
    fontSize: 16,
    opacity: 0.85,
    marginBottom: 24,
    textAlign: "center" as const,
  },
  button: {
    width: "100%",
    padding: "16px 24px",
    fontSize: 18,
    fontWeight: 600,
    borderRadius: 14,
    border: "none",
    background: theme.colors.primary,
    color: theme.colors.text,
    cursor: "pointer",
  },
} as const;
