import type { Question } from "@domain/questions/types";

export const SIGNED_NUMBERS_QUESTIONS: Question[] = [
  // ----------------------------
  // SN_ADD_SAME_SIGN (5)
  // ----------------------------
  {
    id: "SN_SAME_01",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ADD_SAME_SIGN",
    type: "numeric",
    difficulty: 0.2,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "(-7)+(-5)" },
    ],
    correctAnswers: ["-12"],
    misconceptions: ["SIGN_ERROR"],
    tags: ["set:SN_01"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_SAME_02",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ADD_SAME_SIGN",
    type: "numeric",
    difficulty: 0.25,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "3.4+2.6" },
    ],
    correctAnswers: ["6"],
    misconceptions: ["DECIMAL_ADD_ERROR"],
    tags: ["set:SN_01"],
    version: 1,
    input: { allowMinus: true, allowDecimal: true },
  },
  {
    id: "SN_SAME_03",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ADD_SAME_SIGN",
    type: "numeric",
    difficulty: 0.3,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "(-2.5)+(-1.75)" },
    ],
    correctAnswers: ["-4.25"],
    misconceptions: ["SIGN_ERROR", "DECIMAL_ADD_ERROR"],
    tags: ["set:SN_01"],
    version: 1,
    input: { allowMinus: true, allowDecimal: true },
  },
  {
    id: "SN_SAME_04",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ADD_SAME_SIGN",
    type: "singleChoice",
    difficulty: 0.3,
    prompt: [
      {
        kind: "text",
        value: "בלי לחשב בדיוק: האם (-19) + (-4) קטן מ־(-19)?",
      },
    ],
    options: [
      { id: "A", content: [{ kind: "text", value: "כן, קטן יותר" }] },
      { id: "B", content: [{ kind: "text", value: "לא, גדול יותר" }] },
      { id: "C", content: [{ kind: "text", value: "שווה" }] },
      { id: "D", content: [{ kind: "text", value: "אי אפשר לדעת" }] },
    ],
    correctOptionId: "A",
    misconceptions: ["SIGN_INTUITION"],
    tags: ["set:SN_01"],
    version: 1,
  },
  // ----------------------------
  // SN_ADD_OPPOSITE_SIGN (5)
  // ----------------------------
  {
    id: "SN_OPP_01",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ADD_OPPOSITE_SIGN",
    type: "numeric",
    difficulty: 0.25,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "(-8)+3" },
    ],
    correctAnswers: ["-5"],
    misconceptions: ["SIGN_ERROR"],
    tags: ["set:SN_02"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_OPP_02",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ADD_OPPOSITE_SIGN",
    type: "numeric",
    difficulty: 0.3,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "6+(-9)" },
    ],
    correctAnswers: ["-3"],
    misconceptions: ["SIGN_ERROR"],
    tags: ["set:SN_02"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_OPP_03",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ADD_OPPOSITE_SIGN",
    type: "numeric",
    difficulty: 0.35,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "(-3.2)+1.7" },
    ],
    correctAnswers: ["-1.5"],
    misconceptions: ["SIGN_ERROR", "DECIMAL_ADD_ERROR"],
    tags: ["set:SN_02"],
    version: 1,
    input: { allowMinus: true, allowDecimal: true },
  },
  {
    id: "SN_OPP_04",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ADD_OPPOSITE_SIGN",
    type: "numeric",
    difficulty: 0.4,
    prompt: [
      { kind: "text", value: "חשב: " },
      {
        kind: "math",
        latex: "\\left(-\\frac{5}{2}\\right)+\\left(\\frac{3}{4}\\right)",
        display: true,
      },
    ],
    correctAnswers: ["-1.75"], // -7/4
    misconceptions: ["FRACTION_ADD_ERROR", "SIGN_ERROR"],
    tags: ["set:SN_02"],
    version: 1,
    input: { allowMinus: true, allowDecimal: true },
  },

  // ----------------------------
  // SN_SUBTRACT (5)
  // ----------------------------
  {
    id: "SN_SUB_01",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_SUBTRACT",
    type: "numeric",
    difficulty: 0.3,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "5-(-3)" },
    ],
    correctAnswers: ["8"],
    misconceptions: ["SUBTRACT_NEGATIVE_ERROR"],
    tags: ["set:SN_03"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_SUB_02",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_SUBTRACT",
    type: "numeric",
    difficulty: 0.35,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "(-4)-7" },
    ],
    correctAnswers: ["-11"],
    misconceptions: ["SIGN_ERROR", "SUBTRACTION_ERROR"],
    tags: ["set:SN_03"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_SUB_03",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_SUBTRACT",
    type: "numeric",
    difficulty: 0.4,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "(-6)-(-10)" },
    ],
    correctAnswers: ["4"],
    misconceptions: ["SUBTRACT_NEGATIVE_ERROR", "SIGN_ERROR"],
    tags: ["set:SN_03"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_SUB_04",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_SUBTRACT",
    type: "singleChoice",
    difficulty: 0.4,
    prompt: [
      { kind: "text", value: "איזה גדול יותר? " },
      { kind: "math", latex: "A=(-2)-(-9)" },
      { kind: "text", value: " או " },
      { kind: "math", latex: "B=(-2)-9" },
    ],
    options: [
      { id: "A", content: [{ kind: "text", value: "A גדול יותר" }] },
      { id: "B", content: [{ kind: "text", value: "B גדול יותר" }] },
      { id: "C", content: [{ kind: "text", value: "שווים" }] },
      { id: "D", content: [{ kind: "text", value: "אי אפשר לדעת" }] },
    ],
    correctOptionId: "A",
    misconceptions: ["SUBTRACT_NEGATIVE_ERROR", "SIGN_INTUITION"],
    tags: ["set:SN_03"],
    version: 1,
  },

  // ----------------------------
  // SN_MULT_DIV (5)
  // ----------------------------
  {
    id: "SN_MD_01",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_MULT_DIV",
    type: "numeric",
    difficulty: 0.35,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "(-4)\\times(-3)" },
    ],
    correctAnswers: ["12"],
    misconceptions: ["NEGATIVE_MULTIPLY_RULE"],
    tags: ["set:SN_04"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_MD_02",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_MULT_DIV",
    type: "numeric",
    difficulty: 0.4,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "12\\div(-3)" },
    ],
    correctAnswers: ["-4"],
    misconceptions: ["NEGATIVE_DIVIDE_RULE"],
    tags: ["set:SN_04"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_MD_03",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_MULT_DIV",
    type: "numeric",
    difficulty: 0.45,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "(-2.5)\\times4" },
    ],
    correctAnswers: ["-10"],
    misconceptions: ["SIGN_ERROR", "DECIMAL_MULT_ERROR"],
    tags: ["set:SN_04"],
    version: 1,
    input: { allowMinus: true, allowDecimal: true },
  },
  {
    id: "SN_MD_04",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_MULT_DIV",
    type: "numeric",
    difficulty: 0.5,
    prompt: [
      { kind: "text", value: "חשב: " },
      {
        kind: "math",
        latex: "\\left(-\\frac{3}{5}\\right)\\times 10",
        display: true,
      },
    ],
    correctAnswers: ["-6"],
    misconceptions: ["FRACTION_MULT_ERROR", "SIGN_ERROR"],
    tags: ["set:SN_04"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_MD_05",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_MULT_DIV",
    type: "singleChoice",
    difficulty: 0.45,
    prompt: [
      { kind: "text", value: "איזה סימן יהיה לתוצאה? " },
      { kind: "math", latex: "(-8)\\times 7\\times (-2)" },
    ],
    options: [
      { id: "A", content: [{ kind: "text", value: "חיובי" }] },
      { id: "B", content: [{ kind: "text", value: "שלילי" }] },
      { id: "C", content: [{ kind: "text", value: "אפס" }] },
      { id: "D", content: [{ kind: "text", value: "אי אפשר לדעת" }] },
    ],
    correctOptionId: "A",
    misconceptions: ["SIGN_PARITY_MULTIPLICATION"],
    tags: ["set:SN_04"],
    version: 1,
  },

  // ----------------------------
  // SN_ORDER_OF_OPERATIONS (5)
  // ----------------------------
  {
    id: "SN_OOO_01",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ORDER_OF_OPERATIONS",
    type: "numeric",
    difficulty: 0.45,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "-3+7-5" },
    ],
    correctAnswers: ["-1"],
    misconceptions: ["ORDER_OF_OPERATIONS", "SIGN_ERROR"],
    tags: ["set:SN_05"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_OOO_02",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ORDER_OF_OPERATIONS",
    type: "numeric",
    difficulty: 0.5,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "6-(-2+5)" },
    ],
    correctAnswers: ["3"],
    misconceptions: ["PARENTHESIS_SIGN_ERROR", "SUBTRACT_NEGATIVE_ERROR"],
    tags: ["set:SN_05"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_OOO_03",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ORDER_OF_OPERATIONS",
    type: "numeric",
    difficulty: 0.55,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "(-2)\\times(3-7)" },
    ],
    correctAnswers: ["8"],
    misconceptions: ["DISTRIBUTION_SIGN_ERROR", "NEGATIVE_MULTIPLY_RULE"],
    tags: ["set:SN_05"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_OOO_04",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ORDER_OF_OPERATIONS",
    type: "numeric",
    difficulty: 0.6,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "(-12)\\div 3+(-1)\\times 4" },
    ],
    correctAnswers: ["-8"],
    misconceptions: ["ORDER_OF_OPERATIONS", "SIGN_ERROR"],
    tags: ["set:SN_05"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },

  // ----------------------------
  // SN_ABSOLUTE_VALUE (5)
  // ----------------------------
  {
    id: "SN_ABS_01",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ABSOLUTE_VALUE",
    type: "numeric",
    difficulty: 0.35,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "|-9|" },
    ],
    correctAnswers: ["9"],
    misconceptions: ["ABS_CONFUSION"],
    tags: ["set:SN_06"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_ABS_02",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ABSOLUTE_VALUE",
    type: "singleChoice",
    difficulty: 0.45,
    prompt: [
      { kind: "text", value: "איזה נכון? " },
      { kind: "math", latex: "|-3|=-3" },
    ],
    options: [
      { id: "A", content: [{ kind: "text", value: "נכון" }] },
      { id: "B", content: [{ kind: "text", value: "לא נכון" }] },
    ],
    correctOptionId: "B",
    misconceptions: ["ABS_CONFUSION"],
    tags: ["set:SN_06"],
    version: 1,
  },
  {
    id: "SN_ABS_03",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ABSOLUTE_VALUE",
    type: "numeric",
    difficulty: 0.55,
    prompt: [
      { kind: "text", value: "חשב: " },
      { kind: "math", latex: "|-2.5|+|1.2|" },
    ],
    correctAnswers: ["3.7"],
    misconceptions: ["ABS_CONFUSION", "DECIMAL_ADD_ERROR"],
    tags: ["set:SN_06"],
    version: 1,
    input: { allowMinus: true, allowDecimal: true },
  },
  {
    id: "SN_ABS_04",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ABSOLUTE_VALUE",
    type: "numeric",
    difficulty: 0.6,
    prompt: [
      { kind: "text", value: "מצא x כך ש: " },
      { kind: "math", latex: "|x|=6" },
    ],
    correctAnswers: ["6", "-6"],
    misconceptions: ["ABS_SINGLE_SOLUTION_ERROR"],
    tags: ["set:SN_06"],
    version: 1,
    input: { allowMinus: true, allowDecimal: false },
  },
  {
    id: "SN_ABS_05",
    topicId: "SIGNED_NUMBERS",
    subtopic: "SN_ABSOLUTE_VALUE",
    type: "singleChoice",
    difficulty: 0.65,
    prompt: [{ kind: "text", value: "מי קרוב יותר ל־0? A = -0.8 או B = 0.3" }],
    options: [
      { id: "A", content: [{ kind: "text", value: "A" }] },
      { id: "B", content: [{ kind: "text", value: "B" }] },
      { id: "C", content: [{ kind: "text", value: "שווים" }] },
      { id: "D", content: [{ kind: "text", value: "אי אפשר לדעת" }] },
    ],
    correctOptionId: "B",
    misconceptions: ["ABS_DISTANCE_INTUITION", "SIGN_INTUITION"],
    tags: ["set:SN_06"],
    version: 1,
  },
] as const;
