import { useState, type CSSProperties } from "react";
import { DOMAINS, SKILLS, getSkillById } from "../../content/catalog/index.ts";
import type { SkillQuestionDefinition } from "@domain/session/skillQuestionSelector"; import type { StudentHomeData } from "@domain/studentHome/types";
import { contentBackedCatalog } from "@domain/studentHome/contentAvailability";
import { deriveSkillDisplayState, evidenceLabels, fluencyLabel, isAssignmentComplete, skillDisplayLabels, sortAssignments } from "@domain/studentHome/deriveStudentHome";
import { colors } from "@ui/tokens"; import { TopicIcon } from "@ui/icons/TopicIcon"; import type { TopicIconName } from "@ui/icons/types";
type Props = { data: StudentHomeData; definitions: readonly SkillQuestionDefinition[]; onStartAssignment: (skillId: string, assignmentId: string) => void; onOpenDomain: (domainId: string) => void };
export function StudentHomeScreen({ data, definitions, onStartAssignment, onOpenDomain }: Props) {
  const catalog = contentBackedCatalog(DOMAINS, SKILLS, definitions); const assignments = sortAssignments(data.assignments); const [expanded, setExpanded] = useState<Set<string>>(new Set());
  const connectionText = data.connection === "online" ? "מסונכרן" : data.connection === "offline" ? "עובדים במצב לא מקוון" : "שמירה מקומית";
  const toggle = (id: string) => setExpanded((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  return <section className="home-screen"><header><h1>{data.student?.displayName ? `שלום ${data.student.displayName}` : "Atomic Math"}</h1><small>{connectionText}</small>{data.warning ? <small>{data.warning}</small> : null}</header>
    {assignments.length ? <section className="home-section"><h2>העבודה שלי</h2>{assignments.map((assignment) => { const skill = getSkillById(assignment.skillId); const snapshot = data.masteryBySkill[assignment.skillId]; const complete = isAssignmentComplete(assignment, snapshot); return <article key={assignment.assignmentId} className="assignment-card"><strong>{skill?.nameHe ?? assignment.skillId}</strong><span>שליטה: {Math.round(snapshot?.mastery ?? 0)}% · יעד: {assignment.targetMastery}%</span><small>{snapshot ? evidenceLabels[snapshot.evidenceLevel] : evidenceLabels.insufficient}</small><button type="button" className="quiet-button" onClick={() => onStartAssignment(assignment.skillId, assignment.assignmentId)}>{complete ? "תרגול נוסף" : "התחל"}</button></article>; })}</section> : null}
    <section className="home-section"><h2>תרגול חופשי</h2>{catalog.map(({ domain, skills }) => { const accent = colors[domain.colorToken as keyof typeof colors] ?? colors.topicBlue; return <button key={domain.id} type="button" className="domain-launch" style={{ "--domain-accent": accent } as CSSProperties} onClick={() => onOpenDomain(domain.id)}><span className="domain-icon" aria-hidden="true"><TopicIcon name={domain.icon as TopicIconName} size={28} /></span><span><strong>{domain.nameHe}</strong><small>{skills.length} מיומנויות זמינות</small></span><span aria-hidden="true">←</span></button>; })}</section>
    <section className="home-section"><h2>מפת המיומנויות שלי</h2>{catalog.map(({ domain, skills }) => { const isOpen = expanded.has(domain.id); const active = skills.filter((skill) => !["not_started", "needs_support"].includes(deriveSkillDisplayState(data.masteryBySkill[skill.id]))).length; const accent = colors[domain.colorToken as keyof typeof colors] ?? colors.topicBlue; return <section key={domain.id} className="domain-tree" style={{ "--domain-accent": accent } as CSSProperties}><button type="button" className="skill-map-summary" aria-expanded={isOpen} onClick={() => toggle(domain.id)}><span className="domain-icon" aria-hidden="true"><TopicIcon name={domain.icon as TopicIconName} size={28} /></span><span><strong>{domain.nameHe}</strong><small>{active}/{skills.length} מיומנויות בתהליך או בשליטה</small></span><span aria-hidden="true">{isOpen ? "⌃" : "⌄"}</span></button>{isOpen ? <div className="domain-tree__children">{skills.map((skill) => { const snapshot = data.masteryBySkill[skill.id]; const state = deriveSkillDisplayState(snapshot); const fluency = skill.fluency?.enabled ? fluencyLabel(snapshot) : null; return <article key={skill.id} className="mastery-row"><span><strong>{skill.shortNameHe ?? skill.nameHe}</strong><small>{skillDisplayLabels[state]}{fluency ? ` · ${fluency}` : ""}</small></span><span className="mastery-badge">{snapshot?.attemptCount ? `${Math.round(snapshot.mastery)}%` : "—"}</span></article>; })}</div> : null}</section>; })}</section>
  </section>;
}
